app = "odic-esa"
primary_region = "ord"

[build]
  dockerfile = "Dockerfile.prod"

[env]
  AI_BACKEND = "anthropic"

[[services]]
  internal_port = 8000
  processes = ["app"]
  protocol = "tcp"
  
  [[services.ports]]
    handlers = ["http"]
    port = 80
  
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
